kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  type: ExternalName
  externalName: elasticsearch-es-http.kube-logging.svc.cluster.local
  ports:
    - port: 9200
      name: rest
    - port: 80
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: apm-server
spec:
  type: ExternalName
  externalName: apm-server-apm-http.kube-logging.svc.cluster.local
  ports:
    - port: 8200