apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "cubeartisan"}}}'
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: cubeartisan
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  selector:
    matchLabels:
      name: cubeartisan
  template:
    metadata:
      labels:
        name: cubeartisan
    spec:
      containers:
        - name: cubeartisan
          image: "ghcr.io/cubeartisan/cubeartisan:latest"
          imagePullPolicy: Always
          env:
            - name: DISCORD_URL
              value: "https://discord.gg/NKCaZRFU"
            - name: DOWNTIME_ACTIVE
              value: "false"
            - name: ELASTIC_APM_ACTIVE
              value: 'true'
            - name: ELASTIC_APM_CLOUD_PROVIDER
              value: none
            - name: ELASTIC_APM_ENVIRONMENT
              value: "<ENV>"
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTIC_APM_SECRET_TOKEN
            - name: ELASTIC_APM_TRANSACTION_IGNORE_URLS
              value: ""
            - name: ELASTIC_APM_SERVER_URL
              value: "http://apm-server:8200/"
            - name: ELASTIC_APM_SERVICE_NAME
              value: CubeArtisan_beta
            - name: ELASTIC_APM_SERVICE_VERSION
              value: "<TAG>"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTICSEARCH_PASSWORD
            - name: ELASTICSEARCH_URL
              value: "https://elasticsearch:9200/"
            - name: ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: ELASTICSEARCH_USER
            - name: EMAIL_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_PASSWORD
            - name: EMAIL_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_USERNAME
            - name: FLASKROOT
              value: "http://cubeartisan-recommender"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
            - name: MONGODB_AUTH_DB
              value: admin
            - name: MONGODB_DBNAME
              value: "cubeartisan"
            - name: MONGODB_HOST
              value: "mongo-svc"
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: MONGODB_CONNECTION_STRING
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-password
                  key: password
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLICASET
              value: mongo
            - name: MONGODB_USER
              value: cubeartisan
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: SESSION
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION_SECRET
            - name: SITE_HOSTNAME
              value: cubeartisan.net
            - name: SITE_NAME
              value: CubeArtisan (beta)
            - name: SITE_ROOT
              value: https://cubeartisan.net
            - name: SITE_VERSION
              value: "staging"
            - name: SOURCE_REPO
              value: https://github.com/CubeArtisan/cubeartisan
            - name: SUPPORT_EMAIL
              value: support@cubeartisan.net
            - name: SUPPORT_EMAIL_FROM
              value: CubeArtisan Support Team <support@cubeartisan.net>
          ports:
            - containerPort: 5000
              name: cubeartisan
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: 2Gi
            requests:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: 2Gi
          readinessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /version
              port: 5000
            failureThreshold: 30
            periodSeconds: 15
      restartPolicy: Always
      imagePullSecrets:
        - name: github-docker
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50