apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: cubeartisan-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cubeartisan-backend-config
spec:
  timeoutSec: 60
  sessionAffinity:
    affinityType: GENERATED_COOKIE
    affinityCookieTtlSec: 300
