apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 02-external-services.kube.yaml
  - 22-mongodb.kube.yaml
  - 40-cubeartisan.kube.yaml
  - 52-cubeartisan-ingress.kube.yaml
