env:
  browser: true
  jest/globals: true
  node: true
extends:
  - airbnb
  - prettier
plugins:
  - jest
  - prettier
settings:
  import/resolver:
    webpack:
      config: webpack.dev.js
rules:
  # prettier/prettier:
  # - error
  no-console: off
  global-require: off
  no-param-reassign: off
  no-underscore-dangle:
    - error
    - allow: ['_id']
  camelcase:
    - error
    - properties: never
      ignoreDestructuring: true
      ignoreImports: true
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax:
    - error
    - FunctionExpression
    - WithStatement
    - BinaryExpression[operator='in']
  react/jsx-props-no-spreading: off
  react/jsx-filename-extension: off
overrides:
  - files: ['src/**']
    rules:
      no-restricted-imports:
        - error
        - patterns: ['./*', '../*']
