changesetBaseRefs:
  - prod
  - origin/prod

enableMessageNames: false

nodeLinker: node-modules

packageExtensions:
  "@google-cloud/opentelemetry-cloud-trace-exporter@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@mui/system@*":
    dependencies:
      styled-components: '*'
      react-dom: '*'
      react-is: '*'
  "@mui/x-date-pickers@*":
    peerDependencies:
      react-dom: '*'
  "html-webpack-live-reload-plugin@*":
    peerDependencies:
      webpack: "^5"

plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.0.cjs
