apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: kube-logging
  name: elasticsearch
spec:
  version: 7.13.4
  http:
    service:
      spec:
        type: NodePort
  nodeSets:
    - name: zone-a
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms2g -Xmx2g
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1000m
                requests:
                  memory: 4Gi
                  cpu: 1000m