apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: kube-logging
  name: kibana
spec:
  version: 7.13.4
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            limits:
              memory: 2.5Gi
              cpu: 1000m
            requests:
              memory: 2.5Gi
              cpu: 1000m