apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: kube-logging
spec:
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.13.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana