apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cubeartisan
  name: mongo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cubeartisan-staging
  name: mongo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pod-service-endpoint
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:default:mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-service-endpoint
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: cubeartisan
  - kind: ServiceAccount
    name: mongo
    namespace: cubeartisan-staging