apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cubeartisan-cert
spec:
  domains:
    - kibana.cubeartisan.net
    -
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: kube-logging
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: cubeartisan-frontend-config
    networking.gke.io/managed-certificates: cubeartisan-kibana-cert
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - host: kibana.cubeartisan.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601