version: '3'
services:
  cubeartisan-mongodb:
    image: 'mongo'
    volumes:
      - cubeartisan-mongodb-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  cubeartisan:
    build:
      dockerfile: .docker/Dockerfile
      context: ../
    image: ${REPOSITORY}/cubeartisan:${TAG}
    ports:
      - "5000:8080"
    depends_on:
      - "cubeartisan-mongodb"
  cubeartisan-jobs:
    build:
      dockerfile: .docker/Dockerfile.jobs
      context: ../
    image: ${REPOSITORY}/cubeartisan-jobs:${TAG}
    depends_on:
      - "cubeartisan-mongodb"
volumes:
  cubeartisan-mongodb-volume:
