apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cubeartisan-mongodb
  name: cubeartisan-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "27018"
    port: 27018
    targetPort: 27018
  - name: "27019"
    port: 27019
    targetPort: 27019
  selector:
    io.kompose.service: cubeartisan-mongodb
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cubeartisan-mongodb
  name: cubeartisan-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: cubeartisan-mongodb
  template:
    metadata:
      labels:
        io.kompose.service: cubeartisan-mongodb
    spec:
      containers:
      - image: mongo
        name: cubeartisan-mongodb
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: cubeartisan-mongodb-claim
      restartPolicy: Always
      volumes:
      - name: cubeartisan-mongodb-claim
        persistentVolumeClaim:
          claimName: cubeartisan-mongodb-claim
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cubeartisan-mongodb-claim
  name: cubeartisan-mongodb-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cubeartisan
  name: cubeartisan
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    io.kompose.service: cubeartisan
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cubeartisan
  name: cubeartisan
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: cubeartisan
  template:
    metadata:
      labels:
        io.kompose.service: cubeartisan
    spec:
      containers:
        - image: "docker.pkg.github.com/ruler501/cubeartisan/cubeartisan:566bdf63"
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: TCG_PLAYER_PRIVATE_KEY
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: TCG_PLAYER_PRIVATE_KEY
            - name: TCG_PLAYER_PUBLIC_KEY
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: TCG_PLAYER_PUBLIC_KEY
            - name: SESSION_SECRET
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: SESSION_SECRET
            - name: DBNAME
              value: "nodecube"
            - name: SESSION
              valueFrom:
                  secretKeyRef:
                    name: cubeartisansecrets
                    key: SESSION
            - name: FLASKROOT
              value: "http://cubeartisan-recommender"
            - name: PORT
              value: "5000"
            - name: HOST
              value: "http://cubeartisan"
            - name: CUBECOBRA_VERSION
              value: "3.6.0"
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch-external:9200/"
            - name: APM_SERVER_URL
              value: "http://apm-server:8200/"
            - name: MONGODB_URL
              value: "mongodb://cubeartisan-mongodb:27017/nodecube"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
          name: cubeartisan
          ports:
            - containerPort: 5000
              name: cubeartisan-http
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /version
              port: cubeartisan-http
            initialDelaySeconds: 60
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /version
              port: 5000
            failureThreshold: 30
            periodSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80