name: CI Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Update NPM
      run: npm install -g yarn
    - name: Setup
      run: yarn install
    - name: Run the CI script in yarn to check code style and unit tests.
      run: yarn ci