name: Continuous Integration Checks
on: [push, pull_request]
jobs:
  "Continuous_Integration_Checks":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.11.1'
    - name: Setup
      run: yarn install --immutable
    - name: Run the CI script in yarn to check code style and unit tests.
      run: yarn ci
    - name: Check that no files were changed
      run: "git status; [ -z $(git status --porcelain) ]"
