name: Deploy to Staging
on:
  push:
    tags:
      - 'v*'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cubeartisan    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: cubeartisan # Add your deployment name here.
jobs:
  build:
    name: Create Release, Build Docker, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag Name
        run: echo "TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Get Repository Owner
        run: echo "REPOSITORY=`echo "ghcr.io/${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]"`" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GIT_TAG }}
          release_name: Release ${{ env.GIT_TAG }}
          draft: false
          prerelease: false
      - name: Show tag and repo
        run: 'echo "REPOSITORY: $REPOSITORY" && echo "TAG: $TAG"'
      - name: Build the Docker image
        run: docker-compose -f .docker/docker-compose.yml build
      - name: Login to Docker
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} 'ghcr.io'
      - name: Push to github package registry
        run: docker-compose -f .docker/docker-compose.yml push
      # Setup gcloud CLI
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ${GITHUB_WORKSPACE}/kustomize
      - name: Update Image Tag and Version
        run: |-
          cd ${GITHUB_WORKSPACE}/.docker/k8s/staging
          ${GITHUB_WORKSPACE}/kustomize edit set image "$REPOSITORY/cubeartisan:$TAG"
          ${GITHUB_WORKSPACE}/kustomize edit add configmap cubeartisan-version --from-literal=TAG=$TAG
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          cd ${GITHUB_WORKSPACE}/.docker/k8s
          ${GITHUB_WORKSPACE}/kustomize build prod | kubectl apply -f -
      - name: Check Deployment
        run: |-
          kubectl rollout status -n cubeartisan deployment/$DEPLOYMENT_NAME --timeout=600s
          kubectl get -n cubeartisan services -o wide