name: Build Docker For Production
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release, Build Docker, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag Name
        run: echo "TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: Get Repository Owner
        run: echo "REPOSITORY=`echo "ghcr.io/${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]"`" >> $GITHUB_ENV
      - name: Show tag and repo
        run: 'echo "REPOSITORY: $REPOSITORY" && echo "TAG: $TAG"'
      - name: Build the Docker image
        run: docker-compose -f .docker/docker-compose.yml build
      - name: Login to Docker
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} 'ghcr.io'
      - name: Push to github package registry
        run: docker-compose -f .docker/docker-compose.yml push
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false
      - name: Trigger deploy
        run: |
          curl -X POST https://api.github.com/repos/CubeArtisan/cubeartisan-infrastructure/dispatches \
          -H 'Accept: application/json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "deploy_staging", "client_payload": { "repository": "'"$REPOSITORY"'", "tag": "'"$TAG"'" }}'