name: Build Docker Image
on:
  workflow_run:
    workflows:
      - Continuous Integration Checks
    branches:
      - prod
      - dev
    types: completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Tag Name
        run: echo "TAG=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
      - name: Get Repository Owner
        run: echo "REPOSITORY=`echo "ghcr.io/${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]"`" >> $GITHUB_ENV
      - name: Show tag and repo
        run: 'echo "REPOSITORY: $REPOSITORY" && echo "TAG: $TAG"'
      - name: Build the Docker image
        run: docker-compose -f .docker/docker-compose.yml build
      - name: Login to Docker
        run: docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} 'ghcr.io'
      - name: Push to github package registry
        run: docker-compose -f .docker/docker-compose.yml push
